import { defineConfig } from 'vitepress'
import { withMermaid } from 'vitepress-plugin-mermaid'
import { codeReferenceSidebarItems } from './reference-sidebar'

// https://vitepress.dev/reference/site-config
export default withMermaid(
  defineConfig({
    base: '/',
    srcDir: 'pages',
    title: "Pill Docs",
    description: "Guide and API reference for Pill - a modern, free and blazingly fast game engine",
    head: [
      // Google Fonts
      ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
      ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
      ['link', { href: 'https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap', rel: 'stylesheet' }],
      // Favicons (the PNG pair follows the browser theme wherever the SVG
      // favicon is not rasterized, e.g. older Android Chrome)
      ['link', { rel: 'icon', type: 'image/png', href: '/favicons/favicon-96x96.png', sizes: '96x96', media: '(prefers-color-scheme: light)' }],
      ['link', { rel: 'icon', type: 'image/png', href: '/favicons/favicon-96x96-dark.png', sizes: '96x96', media: '(prefers-color-scheme: dark)' }],
      ['link', { rel: 'icon', type: 'image/svg+xml', href: '/favicons/favicon.svg' }],
      ['link', { rel: 'shortcut icon', href: '/favicons/favicon.ico' }],
      ['link', { rel: 'apple-touch-icon', sizes: '180x180', href: '/favicons/apple-touch-icon.png' }],
      ['link', { rel: 'manifest', href: '/favicons/site.webmanifest' }],
      // Social meta
      ['meta', { property: 'og:title', content: 'Pill Docs' }],
      ['meta', { property: 'og:description', content: 'Guide and API reference for Pill Engine' }],
      ['meta', { property: 'og:image', content: '/favicons/web-app-manifest-512x512.png' }],
      ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
      // Analytics (Umami). data-domains keeps the tracker off localhost and
      // preview deployments; both production domain families are listed.
      ['script', { defer: '', src: 'https://umami.campfire-on-the-wall.com/script.js', 'data-website-id': 'be02f2ef-9344-46d7-bc07-c9c56af6531e', 'data-domains': 'pillengine.org,www.pillengine.org,docs.pillengine.org,pill.rocks,www.pill.rocks,docs.pill.rocks' }],
      // Report 404s with the attempted path so broken inbound links show up
      // in the dashboard. The 404 view is client rendered, so the check runs
      // on load and then polls briefly (the static page title is an early
      // signal; .NotFound is the rendered view once the app hydrates).
      ['script', {}, `
        (() => {
          let reported = false;
          const reportMissingPage = () => {
            if (reported) return;
            if (document.querySelector('.NotFound') || document.title.startsWith('404')) {
              reported = true;
              window.umami?.track('page-404', { path: window.location.pathname });
            }
          };
          window.addEventListener('load', reportMissingPage);
          let attempts = 0;
          const poller = setInterval(() => {
            reportMissingPage();
            if (reported || ++attempts >= 12) clearInterval(poller);
          }, 250);
        })();
      `],
      // AI / LLM discovery: curated index generated by scripts/generate-llms.mjs
      ['link', { rel: 'alternate', type: 'text/plain', href: '/llms.txt', title: 'LLM-friendly docs' }]
    ],

    // Points every page at its clean Markdown mirror (written after
    // `vitepress build` by scripts/generate-llms.mjs) so AI agents and tools
    // can request plain Markdown instead of rendered HTML.
    transformHead({ pageData }) {
      return [
        ['link', { rel: 'alternate', type: 'text/markdown', href: `/markdown/${pageData.relativePath}` }],
      ]
    },

    markdown: {
      html: true
    },

    mermaid: {
      flowchart: {
        curve: 'step'
      }
    },

    themeConfig: {
      // https://vitepress.dev/reference/default-theme-config
      siteTitle: 'pill docs',

      nav: [
        {
          text: 'Guide',
          link: '/guide/',
          activeMatch: '^/guide/'
        },
        {
          text: 'Reference',
          link: '/reference/',
          activeMatch: '^/reference/'
        }
      ],

      outline: {
        level: [2, 3],
        label: 'On this page'
      },

      search: {
        provider: 'local'
      },

      sidebar: {
        '/guide/': [
          {
            text: 'Introduction',
            items: [
              {
                text: 'Welcome',
                link: '/guide/'
              },
              {
                text: 'What is Pill?',
                link: '/guide/what-is-pill'
              }
            ],
          },
          {
            text: 'Getting Started',
            items: [
              { text: 'Setup', link: '/guide/getting-started/setup' },
              { text: 'Pill Launcher', link: '/guide/getting-started/pill-launcher' },
              { text: 'ECS (Entity Component System)', link: '/guide/getting-started/ecs' },
              { text: 'Resources', link: '/guide/getting-started/resources' }
            ]
          },
          {
            text: 'Next Steps',
            items: [
              { text: 'Next Steps', link: '/guide/next-steps' }
            ]
          },
          {
            text: 'Help',
            items: [
              { text: 'Troubleshooting', link: '/guide/troubleshooting' }
            ]
          },
          {
            text: 'Advanced',
            items: [
              { text: 'Pill Launcher', link: '/guide/advanced/pill-launcher' },
            ]
          },
          {
            text: 'Engine Development',
            items: [
              {
                text: 'Contributing',
                link: '/guide/contributing/contributing',
                items: [
                  { text: 'Coding Standards', link: '/guide/contributing/coding-standards' },
                  { text: 'Code of Conduct', link: '/guide/contributing/code-of-conduct' },
                ]
              },
              { text: 'CI Pipeline', link: '/guide/advanced/ci-pipeline' }
            ]
          },
          {

            text: 'Other',
            items: [
              { text: 'Brand Identity', link: '/guide/other/brand-identity' },
            ]
          }
        ],
        '/reference/': codeReferenceSidebarItems
      },

      socialLinks: [
        { icon: 'github', link: 'https://github.com/Pillware/Pill' }
      ]
    }
  })
)